### ISSUE TITLE
Can't Checking Tor instance

### ISSUE THREAD

**Issue by buittuan1985** [blueudp/Deep-Explorer#2]
Hi!
When I executive command: python deepexplorer.py
It was error with message:
"Checking Tor instance [[0;31mNot connected[0m]
Starting Tor instance 'service' is not recognized as an internal or external command,
operable program or batch file.
  [OK]
Checking Tor proxy  => [ERROR] proxy is refusing connections
'sudo' is not recognized as an internal or external command,
operable program or batch file."

I installed python 3.7.0 and run " pip install -r requirements.txt"
 Thanks you so much

**Comment by blueudp** [comment]
The problem reside in your OS, deep-explorer is designed for debian, that's why "service" is not recognized, so Tor can't start!!!

**Comment by buittuan1985** [comment]
Thanks for your reply. I will install in Kali Linux and check again

**Comment by forefrontz** [comment]
Hi,

I'm stuck at another step:
---------
Checking Tor instance [Not connected]
Starting Tor instance   [OK]
Checking Tor proxy  => [ERROR] proxy is refusing connections
--------

I cannot get past that "proxy is refusing connections'' at all.
Tor browser is running without any problems though.

Any idea what I can do?
Thank you very much!
